server:
  port: 8085
spring:
  application:
    name: service-inventory
  datasource:
    url: jdbc:postgresql://localhost:5436/food_ordering_inventory
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
